### ISSUE TITLE
Problem with exporting to Google Drive

### ISSUE THREAD

**Issue by BUSHA** [GDG-Ukraine/gdgregform#1] opened 2013-05-09 22:02 UTC
"Strange response:{}" when exporting  to Google Drive.

**Comment by webknjaz** [comment] 2013-05-09 22:04
I consider that the root of this issue is an out-of-date google token. Earlier @olostan promised to fix this. Try re-login, this should help.

**Comment by olostan** [comment] 2013-05-10 20:26
Commit https://github.com/GDG-Ukraine/gdgregform/commit/4554657e8bc86ff736ba5e014ab1bbf48801df8e should fix issue. check (login and then after several hours try to send to drive)

**Comment by webknjaz** [comment] 2013-05-11 11:49
@olostan got this issue a couple hours ago. It seems fix didn't really fix the root of issue.

**Comment by olostan** [comment] 2013-05-13 09:01
Just committed change that will help to identify source of this issue. If someone will get the error message while sending to Google Drive, please open console (Ctrl-Shift-J) and copy/paste error message here.

**Comment by olostan** [comment] 2013-05-16 09:12
Can't reproduce... re-logged today (without restarting server for a several days) and was able to export to GDrive... Can somebody confirm that this issue still happen?

**Comment by webknjaz** [comment] 2013-05-16 11:29
Didn't face the issue since my previous comment. Closed.

**Comment by webknjaz** [comment] 2015-05-19 10:57
@bluebirrd has reported that the issue still exists and I confirm this. See traceback from heroku logs below:

```
2015-05-19T09:59:37.041008+00:00 app[web.1]: TypeError: Object true has no method 'indexOf'
2015-05-19T09:59:37.041015+00:00 app[web.1]:     at /app/server/api/gevents.js:305:31
2015-05-19T09:59:37.041017+00:00 app[web.1]:     at Array.forEach (native)
2015-05-19T09:59:37.041018+00:00 app[web.1]:     at /app/server/api/gevents.js:297:24
2015-05-19T09:59:37.041019+00:00 app[web.1]:     at null.<anonymous> (/app/server/api/gevents.js:41:17)
2015-05-19T09:59:37.041021+00:00 app[web.1]:     at EventEmitter.emit (events.js:106:17)
2015-05-19T09:59:37.041022+00:00 app[web.1]:     at module.exports.CustomEventEmitter.emit (/app/node_modules/sequelize/lib/emitters/custom-event-emitter.js:61:33)
2015-05-19T09:59:37.041024+00:00 app[web.1]:     at module.exports.finish (/app/node_modules/sequelize/lib/query-chainer.js:142:30)
2015-05-19T09:59:37.041025+00:00 app[web.1]:     at null.<anonymous> (/app/node_modules/sequelize/lib/query-chainer.js:114:16)
2015-05-19T09:59:37.041026+00:00 app[web.1]:     at EventEmitter.emit (events.js:95:17)
2015-05-19T09:59:37.041028+00:00 app[web.1]:     at module.exports.CustomEventEmitter.emit (/app/node_modules/sequelize/lib/emitters/custom-event-emitter.js:61:33)
2015-05-19T10:00:06.922483+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/api/events/45/report?mode=all" host=reg.gdg.org.ua request_id=89a5a83e-450f-44c1-b97a-8f131e5d09f1 fwd="195.191.13.80" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0
```

**Closed as completed** 2015-05-19 12:07 UTC
Labels: bug, check fix
